export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CART_CLEAR_ITEM = 'CART_CLEAR_ITEM';

export const CART_SHIPPING_SAVE_ITEM = 'CART_SHIPPING_SAVE_ITEM';

export const CART_PAYMENT_METHOD_ITEM = 'CART_PAYMENT_METHOD_ITEM';
